{
 "title": "Alerts Overall CI Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Alert_http_responseCodes_serverError_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_responseCodes_serverError_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Alert_jenkins_uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "default_jenkins_uptime", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Alert_http_responseCodes_serviceUnavailable_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_responseCodes_serviceUnavailable_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Alert_kubernetes_cloud_pods_created",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kubernetes_cloud_pods_created", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Alert_jenkins_plugins_failed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_plugins_failed", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Alert_kube_node_spec_unschedulable",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kube_node_spec_unschedulable", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Alert_jenkins_health_check_score",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_health_check_score", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Alert_jenkins_runs_success_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_runs_success_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Alert_process_virtual_memory_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"c1.default.svc.cluster.local:80\", job=\"c1-metrics\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=\"c2.default.svc.cluster.local:80\", job=\"c2-metrics\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Alert_jenkins_queue_size_value",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_queue_size_value", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Alert_system_cpu_load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "system_cpu_load", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Alert_jenkins_node_online_value",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_node_online_value", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}