{
 "title": "CJOC_Listeners",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "cloudbees_platform_data_relay_SecurityListener_onUserCreated_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_SecurityListener_onUserCreated_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_NodeListener_onUpdated_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_NodeListener_onUpdated_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_SecurityListener_onLoggedOut_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_SecurityListener_onLoggedOut_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_NodeListener_onDeleted_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_NodeListener_onDeleted_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_SecurityListener_onLoggedIn_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_SecurityListener_onLoggedIn_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_ItemListener_onUpdated_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_ItemListener_onUpdated_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_SecurityListener_onFailedToLogIn_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_SecurityListener_onFailedToLogIn_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_ItemListener_onRenamed_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_ItemListener_onRenamed_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_SecurityListener_onFailedToAuthenticate_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_SecurityListener_onFailedToAuthenticate_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_ItemListener_onInstalled_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_ItemListener_onInstalled_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_SecurityListener_onAuthenticated_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_SecurityListener_onAuthenticated_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_ItemListener_onCreated_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_ItemListener_onCreated_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_SCMListener_onCheckout_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_SCMListener_onCheckout_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_ItemListener_onChanged_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_ItemListener_onChanged_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_SCMListener_onChangeLogParsed_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_SCMListener_onChangeLogParsed_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_ComputerListener_onTemporarilyOffline_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_ComputerListener_onTemporarilyOffline_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_SaveableListener_onJenkinsChange_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_SaveableListener_onJenkinsChange_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_ComputerListener_onOffline_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_ComputerListener_onOffline_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_RunListener_onStarted_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_RunListener_onStarted_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_RunListener_onInitialize_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_RunListener_onInitialize_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_RunListener_onFinalized_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_RunListener_onFinalized_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_RunListener_onDeleted_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_RunListener_onDeleted_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_RunListener_onCompleted_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_RunListener_onCompleted_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_RestartListener_onStart_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_RestartListener_onStart_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_RestartListener_onRestart_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_RestartListener_onRestart_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_RestartListener_onConfigurationChange_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_RestartListener_onConfigurationChange_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_QueueItemMetricsListener_onTaskStarted_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_QueueItemMetricsListener_onTaskStarted_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_QueueItemMetricsListener_onTaskQueued_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_QueueItemMetricsListener_onTaskQueued_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_QueueItemMetricsListener_onTaskFinished_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_QueueItemMetricsListener_onTaskFinished_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_QueueItemMetricsListener_onTaskCancelled_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_QueueItemMetricsListener_onTaskCancelled_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_QueueItemMetricsListener_onRunStarted_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 168 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_QueueItemMetricsListener_onRunStarted_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_QueueItemMetricsListener_onRunFinished_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 176 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_QueueItemMetricsListener_onRunFinished_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_QueueItemMetricsListener_onJobQueued_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 184 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_QueueItemMetricsListener_onJobQueued_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_QueueItemMetricsListener_onJobCancelled_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 192 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_QueueItemMetricsListener_onJobCancelled_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_PluginUsageListener_onPluginUsedInSystemConfiguration_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 200 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_PluginUsageListener_onPluginUsedInSystemConfiguration_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_PluginUsageListener_onPluginUsedInPipeline_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 208 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_PluginUsageListener_onPluginUsedInPipeline_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_PluginUsageListener_onPluginUsedInItemConfiguration_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 216 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_PluginUsageListener_onPluginUsedInItemConfiguration_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_PluginUsageListener_onPluginUsedAsDependency_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 224 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_PluginUsageListener_onPluginUsedAsDependency_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_NodeListener_onCreated_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 232 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_NodeListener_onCreated_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_ItemListener_onUninstalled_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 240 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_ItemListener_onUninstalled_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_ItemListener_onLocationChanged_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 248 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_ItemListener_onLocationChanged_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_ItemListener_onDeleted_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 256 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_ItemListener_onDeleted_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_ItemListener_onCopied_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 264 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_ComputerListener_onTemporarilyOnline_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 272 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_ComputerListener_onTemporarilyOnline_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_ComputerListener_onOnline_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 280 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_ComputerListener_onOnline_count"
    }
   ]
  },
  {
   "title": "cloudbees_platform_data_relay_ComputerListener_onLaunchFailure_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 288 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudbees_platform_data_relay_ComputerListener_onLaunchFailure_count"
    }
   ]
  }
 ]
}