{
 "title": "Jobs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "jenkins_job_scheduled_last_hour",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "rate(jenkins_job_scheduled_total[1h])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jenkins_job_total_duration_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins_job_total_duration_count"
    }
   ]
  },
  {
   "title": "jenkins_job_execution_time_last_hour (Mean)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "rate(jenkins_job_execution_time_count[1h])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jenkins_job_building_duration_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins_job_building_duration_count"
    }
   ]
  },
  {
   "title": "jenkins_job_blocked_duration_count_mean_last_hour",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "rate(jenkins_job_blocked_duration_count[1h])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jenkins_job_count_value",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_job_count_value" }
   ]
  },
  {
   "title": "jenkins_job_queuing_duration_count (Mean last hour)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "rate(jenkins_job_queuing_duration_count[1h])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jenkins_job_averageDepth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_job_averageDepth" }
   ]
  },
  {
   "title": "jenkins_job_waiting_duration_mean_last_hour",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "rate(jenkins_job_waiting_duration_count[1h])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jenkins_job_buildable_duration_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins_job_buildable_duration_count"
    }
   ]
  },
  {
   "title": "jenkins_job_count_history_last_hour",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "rate(jenkins_job_count_history_count[1h])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}