{
 "title": "kubernetes",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "kubernetes_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kubernetes_total" }
   ]
  },
  {
   "title": "kubernetes_successRate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kubernetes_successRate" }
   ]
  },
  {
   "title": "kubernetes_failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kubernetes_failure" }
   ]
  },
  {
   "title": "kubernetes_success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kubernetes_success" }
   ]
  },
  {
   "title": "kubernetes_client_connections_queued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubernetes_client_connections_queued"
    }
   ]
  },
  {
   "title": "kubernetes_client_connections_running",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubernetes_client_connections_running"
    }
   ]
  },
  {
   "title": "kubernetes_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kubernetes_count" }
   ]
  }
 ]
}