{
 "title": "Overall CI Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pods (4builds) created per Controller",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "kubernetes_cloud_pods_created", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jenkins_job_count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jenkins_job_count_value", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "http_responseCodes_ok_total",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "rate(http_responseCodes_ok_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "http_serviceUnavailable_total",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(http_responseCodes_serviceUnavailable_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jenkins_job_scheduled",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jenkins_job_scheduled_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Unschedulable Nodes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "kube_node_spec_unschedulable", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "http_serverError_total",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "rate(http_responseCodes_serverError_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jenkins_job_blocked_duration_count_mean_last_hour",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(jenkins_job_blocked_duration_count[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jenkins_runs_success_total",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jenkins_runs_success_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jenkins_runs_total",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jenkins_runs_total_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "http_badRequest_total",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "rate(http_responseCodes_badRequest_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jenkins_job_waiting_duration_mean_last_hour",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "rate(jenkins_job_waiting_duration_count[1h])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Jenkins Queue Size",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jenkins_queue_size_value", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jvm_memory_bytes_committed_HEAP",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_committed{area=\"heap\",}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jenkins_job_queuing_duration_count (Mean last hour)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "rate(jenkins_job_queuing_duration_count[1h])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jenkins_uptime",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "default_jenkins_uptime", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jvm_memory_bytes_committed_NONHEAP",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_committed{area=\"nonheap\",}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "system_cpu_load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "system_cpu_load", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jenkins_job_execution_time_last_hour (Mean)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "rate(jenkins_job_execution_time_count[1h])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jvm_memory_bytes_used_HEAP",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "process_virtual_memory_bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"c1.default.svc.cluster.local:80\", job=\"c1-metrics\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=\"c2.default.svc.cluster.local:80\", job=\"c2-metrics\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jvm_memory_bytes_used_NONHEAP",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\",}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jenkins_node_online",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jenkins_node_online_value", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jenkins_plugins_active",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jenkins_plugins_active", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jvm_threads_TERMINATED",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "jvm_threads_state{state=\"TERMINATED\",}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jenkins_health_check_score",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jenkins_health_check_score", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jenkins_plugins_failed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jenkins_plugins_failed", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jvm_threads_BLOCKED",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "jvm_threads_state{state=\"BLOCKED\",}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jenkins_executor_count_value",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jenkins_executor_count_value", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jenkins_plugins_withUpdate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jenkins_plugins_withUpdate", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jenkins_project_count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jenkins_project_count_value", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jenkins_plugins_inactive",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jenkins_plugins_inactive", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}