{
 "title": "Plugins",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "jenkins_plugins_withUpdate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jenkins_plugins_withUpdate", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jenkins_plugins_failed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jenkins_plugins_failed", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jenkins_plugins_inactive",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jenkins_plugins_inactive", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jenkins_plugins_active",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jenkins_plugins_active", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}