{
 "title": "Servlet Container Info",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "jenkins_servlet_container_workersStatusTimeWait_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins_servlet_container_workersStatusTimeWait_count"
    }
   ]
  },
  {
   "title": "jenkins_servlet_container_workersStatusBlocked_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins_servlet_container_workersStatusBlocked_count"
    }
   ]
  },
  {
   "title": "jenkins_servlet_container_workers_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins_servlet_container_workers_count"
    }
   ]
  },
  {
   "title": "jenkins_servlet_container_threadsCounter_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins_servlet_container_threadsCounter_count"
    }
   ]
  },
  {
   "title": "jenkins_servlet_container_active_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins_servlet_container_active_count"
    }
   ]
  }
 ]
}