{
 "title": "systemMetrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "totalLoggingOutputMeter_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "totalLoggingOutputMeter_total" }
   ]
  },
  {
   "title": "unrestrictedApiCallsMeter_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "unrestrictedApiCallsMeter_total"
    }
   ]
  },
  {
   "title": "process_cpu_seconds_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_cpu_seconds_total" }
   ]
  },
  {
   "title": "process_open_fds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_open_fds" }
   ]
  },
  {
   "title": "system_cpu_load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "system_cpu_load" }
   ]
  },
  {
   "title": "process_virtual_memory_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"c1.default.svc.cluster.local:80\", job=\"c1-metrics\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=\"c2.default.svc.cluster.local:80\", job=\"c2-metrics\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}