{
 "title": "CI_JVM_Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "jvm_threads_state_TERMINATED",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{state=\"TERMINATED\",}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jvm_memory_bytes_committed_HEAP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_committed{area=\"heap\",}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jvm_threads_state_WAITING",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{state=\"WAITING\",}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jvm_memory_bytes_committed_NONHEAP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_committed{area=\"nonheap\",}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jvm_threads_state_RUNNABLE",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{state=\"RUNNABLE\",}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jvm_memory_bytes_used_NONHEAP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\",}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jvm_threads_state_NEW",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{state=\"NEW\",}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jvm_memory_bytes_used_HEAP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jvm_threads_state_TIMED_WAITING",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{state=\"TIMED_WAITING\",}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jvm_threads_state_BLOCKED",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{state=\"BLOCKED\",}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jvm_threads_current",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_current", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}