{
 "title": "Disk Utilization",
 "time": { "from": "2021-03-09T14:42:46.756Z", "to": "2021-03-09T15:07:17.488Z" },
 "panels": [
  {
   "title": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/workflow-libs\",}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/workflow-libs\",}"
    }
   ]
  },
  {
   "title": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/users\",}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/users\",}"
    }
   ]
  },
  {
   "title": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/userContent\",}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/userContent\",}"
    }
   ]
  },
  {
   "title": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/updates\",}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/updates\",}"
    }
   ]
  },
  {
   "title": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/slow-requests\",}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/slow-requests\",}"
    }
   ]
  },
  {
   "title": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/support\",}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/support\",}"
    }
   ]
  },
  {
   "title": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/plugins\",}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/plugins\",}"
    }
   ]
  },
  {
   "title": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/secrets\",}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/secrets\",}"
    }
   ]
  },
  {
   "title": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/optional-plugins\",}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/optional-plugins\",}"
    }
   ]
  },
  {
   "title": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/nodes\",}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/nodes\",}"
    }
   ]
  },
  {
   "title": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/lost+found\",}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/lost+found\",}"
    }
   ]
  },
  {
   "title": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/logs\",}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/logs\",}"
    }
   ]
  },
  {
   "title": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/jobs\",}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/jobs\",}"
    }
   ]
  },
  {
   "title": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/license-activated-or-renewed-after-expiration.groovy.d\",}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/license-activated-or-renewed-after-expiration.groovy.d\",}"
    }
   ]
  },
  {
   "title": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/high-load\",}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/high-load\",}"
    }
   ]
  },
  {
   "title": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/init.groovy.d\",}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/init.groovy.d\",}"
    }
   ]
  },
  {
   "title": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/dumb-waiter\",}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/dumb-waiter\",}"
    }
   ]
  },
  {
   "title": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/envelope-extension\",}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/envelope-extension\",}"
    }
   ]
  },
  {
   "title": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/cb-envelope\",}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/cb-envelope\",}"
    }
   ]
  },
  {
   "title": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/deadlocks\",}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/deadlocks\",}"
    }
   ]
  },
  {
   "title": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/.groovy\",}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/.groovy\",}"
    }
   ]
  },
  {
   "title": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/.java\",}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/.java\",}"
    }
   ]
  },
  {
   "title": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME\",}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME\",}"
    }
   ]
  },
  {
   "title": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/.cache\",}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_disk_usage_bytes{directory=\"JENKINS_HOME/.cache\",}"
    }
   ]
  },
  {
   "title": "Temp Dir",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_disk_usage_bytes{directory=\"java.io.tmpdir\",}"
    }
   ]
  }
 ]
}