{
 "title": "httpInfo",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "httpRequest-Count Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "http_requests_count", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "httpActiveRequest",
   "type": "gauge",
   "description": "httpActiveRequest",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "(http_activeRequests)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "http_responseCodes_ok_total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "http_responseCodes_ok_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "% http_responseCodes_ok_total vs total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(http_responseCodes_ok_total) / (http_responseCodes_badRequest_total + http_responseCodes_created_total + http_responseCodes_forbidden_total + http_responseCodes_noContent_total + http_responseCodes_notFound_total + http_responseCodes_notModified_total + http_responseCodes_ok_total + http_responseCodes_other_total + http_responseCodes_serverError_total)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "http_responseCodes_serverError_total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "http_responseCodes_serverError_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "% http_responseCodes_serverError vs total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(http_responseCodes_serverError_total) / (http_responseCodes_badRequest_total + http_responseCodes_created_total + http_responseCodes_forbidden_total + http_responseCodes_noContent_total + http_responseCodes_notFound_total + http_responseCodes_notModified_total + http_responseCodes_ok_total + http_responseCodes_other_total + http_responseCodes_serverError_total)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "http_responseCodes_serviceUnavailable_total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "http_responseCodes_serviceUnavailable_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "% http_responseCodes_serviceUnavailable vs total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(http_responseCodes_serviceUnavailable_total) / (http_responseCodes_badRequest_total + http_responseCodes_created_total + http_responseCodes_forbidden_total + http_responseCodes_noContent_total + http_responseCodes_notFound_total + http_responseCodes_notModified_total + http_responseCodes_ok_total + http_responseCodes_other_total + http_responseCodes_serverError_total)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "http_responseCodes_forbidden_total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "http_responseCodes_forbidden_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "% http_responseCodes_forbidden vs total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(http_responseCodes_forbidden_total) / (http_responseCodes_badRequest_total + http_responseCodes_created_total + http_responseCodes_forbidden_total + http_responseCodes_noContent_total + http_responseCodes_notFound_total + http_responseCodes_notModified_total + http_responseCodes_ok_total + http_responseCodes_other_total + http_responseCodes_serverError_total)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "http_responseCodes_badRequest_total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "http_responseCodes_badRequest_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "% http_responseCodes_badRequest vs total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(http_responseCodes_badRequest_total) / (http_responseCodes_badRequest_total + http_responseCodes_created_total + http_responseCodes_forbidden_total + http_responseCodes_noContent_total + http_responseCodes_notFound_total + http_responseCodes_notModified_total + http_responseCodes_ok_total + http_responseCodes_other_total + http_responseCodes_serverError_total)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}