{
 "title": "JenkinsQueue",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "jenkins_queue_stuck_value",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(jenkins_queue_stuck_value[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jenkins_queue_pending_value",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(jenkins_queue_pending_value[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jenkins_queue_size_value",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_queue_size_value" }
   ]
  },
  {
   "title": "jenkins_queue_blocked_value",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(jenkins_queue_blocked_value[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jenkins_queue_buildable_value",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(jenkins_queue_buildable_value[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}