{
 "title": "JenkinsRuns",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "jenkins_runs_total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jenkins_runs_total_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jenkins_runs_success",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jenkins_runs_success_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jenkins_runs_success / jenkins_runs_total_total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(jenkins_runs_success_total)/(jenkins_runs_total_total)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jenkins_runs_unstable",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jenkins_runs_unstable_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jenkins_runs_unstable / jenkins_runs_total_total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(jenkins_runs_unstable_total)/(jenkins_runs_total_total)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jenkins_runs_not_built",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jenkins_runs_not_built_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jenkins_runs_not_built / jenkins_runs_total_total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(jenkins_runs_not_built_total) / (jenkins_runs_total_total)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jenkins_runs_aborted",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jenkins_runs_aborted_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jenkins_runs_aborted / jenkins_runs_total_total",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "jenkins_runs_aborted_total / jenkins_runs_total_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jenkins_runs_failure",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jenkins_runs_failure_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jenkins_runs_failure / jenkins_runs_total_total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "jenkins_runs_failure_total / jenkins_runs_total_total",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}