{
 "title": "JenkinsProjects",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "jenkins_project_count_value",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jenkins_project_count_value", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jenkins_project_disabled_count_value",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "jenkins_project_disabled_count_value",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "% jenkins_project_disabled_count_value vs total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(jenkins_project_disabled_count_value) / (jenkins_project_count_value)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jenkins_project_enabled_count_value",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "jenkins_project_enabled_count_value",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "% jenkins_project_enabled_count_value vs total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(jenkins_project_enabled_count_value) / (jenkins_project_count_value)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}