{
 "title": "JenkinsNodes-Info",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "jenkins_node_online_value",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(jenkins_node_online_value[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jenkins_node_count_value",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(jenkins_node_count_value[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jenkins_node_offline_value",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(jenkins_node_offline_value[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jenkins_node_count_history_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins_node_count_history_count"
    }
   ]
  }
 ]
}