{
 "title": "Jobs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "jenkins_job_count_value",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jenkins_job_count_value" }
   ]
  },
  {
   "title": "jenkins_job_scheduled_total",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jenkins_job_scheduled_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jenkins_job_waiting_duration_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins_job_waiting_duration_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "% jenkins_job_waiting_duration_count vs total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(jenkins_job_waiting_duration_count) / (jenkins_job_blocked_duration_count + jenkins_job_buildable_duration_count + jenkins_job_building_duration_count + jenkins_job_waiting_duration_count + jenkins_job_queuing_duration_count + jenkins_job_execution_time_count)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jenkins_job_execution_time_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins_job_execution_time_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "% jenkins_job_execution_time_count vs total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(jenkins_job_execution_time_count) / (jenkins_job_blocked_duration_count + jenkins_job_buildable_duration_count + jenkins_job_building_duration_count + jenkins_job_waiting_duration_count + jenkins_job_queuing_duration_count + jenkins_job_execution_time_count)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jenkins_job_blocked_duration_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins_job_blocked_duration_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "% jenkins_job_blocked_duration_count vs total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(jenkins_job_blocked_duration_count)/ (jenkins_job_blocked_duration_count + jenkins_job_buildable_duration_count + jenkins_job_building_duration_count + jenkins_job_waiting_duration_count + jenkins_job_queuing_duration_count + jenkins_job_execution_time_count)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jenkins_job_queuing_duration_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins_job_queuing_duration_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "% jenkins_job_queuing_duration_count vs total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(jenkins_job_queuing_duration_count) / (jenkins_job_blocked_duration_count + jenkins_job_buildable_duration_count + jenkins_job_building_duration_count + jenkins_job_waiting_duration_count + jenkins_job_queuing_duration_count + jenkins_job_execution_time_count)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jenkins_job_buildable_duration_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins_job_buildable_duration_count"
    }
   ]
  },
  {
   "title": "% jenkins_job_buildable_duration_count vs total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(jenkins_job_buildable_duration_count) / (jenkins_job_blocked_duration_count + jenkins_job_buildable_duration_count + jenkins_job_building_duration_count + jenkins_job_waiting_duration_count + jenkins_job_queuing_duration_count + jenkins_job_execution_time_count)"
    }
   ]
  },
  {
   "title": "jenkins_job_building_duration_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins_job_building_duration_count"
    }
   ]
  },
  {
   "title": "jenkins_job_building_duration_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(jenkins_job_building_duration_count) / (jenkins_job_blocked_duration_count + jenkins_job_buildable_duration_count + jenkins_job_building_duration_count + jenkins_job_waiting_duration_count + jenkins_job_queuing_duration_count + jenkins_job_execution_time_count)"
    }
   ]
  }
 ]
}